CREATE DATABASE IF NOT EXISTS flattened;
GRANT ALL PRIVILEGES ON flattened.* TO 'openmrs'@'%';
GRANT REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'openmrs'@'%';
FLUSH PRIVILEGES;

SHOW VARIABLES LIKE 'log_bin';